spring.application.name=patientSmartQR
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

user-password= $2a$10$ys3VEzxC/zm4hRcHBZdakOVGjRniSa4.nG5Q3pCgm/b2Tk4gf/CWO
user-name = admin@gmail.com
first-name = Admin
